class StyleSheet:
    correctAnswerLabel = (
        u"color: rgb(20, 194, 4);\n"
        "padding: 10px;\n"
        "font-size: 18px;\n"
        "font-weight: 400;\n"
        "background-color: white;\n"
        "border-bottom-left-radius: 10px;\n"
        "border-bottom-right-radius: 10px;\n"
        "margin: 0 10px;\n"
        )
    wrongAnswerLabel = (
        u"color: rgb(203, 46, 46);"
        "padding: 10px;\n"
        "font-size: 18px;\n"
        "font-weight: 400;\n"
        "background-color: white;\n"
        "border-bottom-left-radius: 10px;\n"
        "border-bottom-right-radius: 10px;\n"
        "margin: 0 10px;\n"
        )
    btnExamSelected = (
        u"color: white;\n"
        "background-color: rgb(62, 162, 255);\n"
        "border-radius: 5px;\n"
        "border: 2px solid rgb(62, 162, 255);\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
    )
    btnExamNotSelected = (
        u"color: rgb(62, 162, 255);\n"
        "border-radius: 5px;\n"
        "background-color: white;\n"
        "border: 2px solid rgb(62, 162, 255);\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
    )
    btnExamSelected = (
        "QPushButton:enabled {\n"
        "color: white;\n"
        "border-radius: 5px;\n"
        "background-color: rgb(42, 142, 255);\n"
        "border: 2px solid rgb(42, 142, 255);\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
        "}\n"
        "QPushButton:disabled {\n"
        "color: rgb(232, 162, 255);\n"
        "border-radius: 5px;\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
        "border: 2px solid rgb(118, 152, 184);\n"
        "color: rgb(118, 152, 184);\n"
        "background-color: rgb(227, 227, 227);\n"
        "}\n"
    )
    btnExamNotSelected = (
        "QPushButton:enabled {\n"
        "color: rgb(62, 162, 255);\n"
        "border-radius: 5px;\n"
        "background-color: 'white';\n"
        "border: 2px solid rgb(62, 162, 255);\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
        "}\n"
        "QPushButton:disabled {\n"
        "color: rgb(62, 162, 255);\n"
        "border-radius: 5px;\n"
        "padding: 7px;\n"
        "padding-left: 15px;\n"
        "padding-right: 15px;\n"
        "font-weight: 500;\n"
        "border: 2px solid rgb(118, 152, 184);\n"
        "color: rgb(118, 152, 184);\n"
        "background-color: rgb(227, 227, 227);\n"
        "}\n"
        "QPushButton:hover {\n"
        "background-color: rgb(42, 142, 255);\n"
        "color: white;\n"
        "border-color: rgb(42, 142, 255);\n"
        "}\n"
    )
